name: soundpool_web
description: A Flutter Sound Pool for playing short audio files. Sound tracks are cached in memory and played directly from cache.
version: 1.0.3
homepage: https://github.com/ukasz123/soundpool/tree/master/soundpool_web

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter
  
  soundpool_platform_interface: 
    git: 
      url: https://github.com/nk2IsHere/soundpool.git
      path: soundpool_platform_interface
  
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: SoundpoolPlugin
        fileName: soundpool_web.dart